version: '3.8'
services:
  mysql:
    image: mysql:5.7.41
    restart: always
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql:/data/db
volumes:
  mysql:

